name: Node CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Make CLI tool globally available
      run: npm link
    - name: Build
      run: npm run build --if-present
    - name: Lint
      run: npm run lint --if-present
    - name: Test
      run: npx jest
      env:
        NODE_OPTIONS: --experimental-vm-modules
        DEBUG: nock*